module.exports = {
  user: "用户名或密码不能为空！",
  userHas: "用户名已经被占用，请更换用户名",
  identity: "身份认证失败！",
  reg: "注册成功",
  regErr: "注册失败",
  loginErr: "登录失败",
  login: "登录成功",
  loginPas: "密码错误",
  userUpdatePas: "密码错误",
  userInfo: "获取用户基本信息成功！",
  userErr: "用户不存在！",
  success: "请求成功",
  error: "请求失败",
  id: "ID不能为空",
  idIsNum: "ID必须是数字",
  update: "更新成功",
  delete: "删除成功",
  userUp: "修改用户信息成功！",
  passwordUp: "更新密码成功！",
  avatar: "更新头像成功",
  getCates: "获取文章分类列表成功！",
  addcates: "新增文章分类成功！",
  deleteCates: "删除文章分类成功！",
  getCatesId: "根据ID获取文章分类数据成功！",
  upCates: "更新分类信息成功！",
};
